before_install:
  - sudo apt-get update
  - sudo apt-get -y install pandoc make
  - pandoc --version

script:
  # create docs directory for pandoc output
  - mkdir docs

  # Generate reveal.js powered HTML from Markdown using make
  - for FOLDER in $(ls -d */ | grep -v 'filters'); do make build FOLDER_NAME=docs/$FOLDER; done

# Deploy to GitHub pages (see https://docs.travis-ci.com/user/deployment/pages/)
deploy:
  provider: pages
  local_dir: docs
  cleanup: false
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  target_branch: gh-pages # Deploy to the gh-pages branch
  on:
    branch: master