version: '3.7'

services:
  presentation:
    build: .
    # user: 1001:1001 
    volumes:
      - .:/data
    ports:
      - "8000:8000"
    command: " --standalone -t revealjs -o /data/presentation.html -s /data/presentation.md -V theme=$solarized -V revealjs-url=https://revealjs.com"
    
volumes:
  presentation:
    driver: local
  slides:
    driver: local