version: '3.7'
# TDOO: add the command to serve the slides in the browser
services:
  presentation:
    build: .
    # user: 1001:1001 
    volumes:
      - .:/reveal.js/content
    ports:
      - 8000:8000
    # command: bash -c "pandoc --standalone -t revealjs -o test.html -s /reveal.js/content/slide.md -V theme=$solarized -V revealjs-url=https://revealjs.com"
    # sleep inifinity to keep the container running
    command: sleep infinity
    
volumes:
  presentation:
    driver: local
  slides:
    driver: local