version: '3.7'
services:
  presentation:
    build: .
    volumes:
      - .:/presentation
    ports:
      - 8000:8000
    command: python3 ./py_scripts/live_server.py --folder slides --port 8000

volumes:
  presentation:
    driver: local
  slides:
    driver: local
