version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            sudo apt-get update
            sudo apt-get -y install pandoc make
            pandoc --version
      - run:
          name: Building the reveal.js presentation slides
          command: |
            for PROJ in $(basename -a $(ls -d */ | grep -v 'filters')); do
              if [ -f $PROJ/config.yml ]; then
                make build FOLDER=$PROJ;
              else
                echo "No config.yml in $PROJ. Skipping...";
              fi;
            done
      - persist_to_workspace:
          root: .
          paths:
            - build
  deploy:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Set Git user information
          command: |
            git config --global user.email "kirubel.m.tadesse@gmail.com"
            git config --global user.name "kirubeltadesse"
      - run:
          name: Checkout gh-pages branch and copy files
          command: |
            git fetch origin gh-pages
            git checkout gh-pages
            ls -la
            cp -r build/. .
            touch .nojekyll
            git add .
      - run:
          name: Deploy to GitHub Pages
          command: |
            if [[ -n $(git status --porcelain) ]]; then
              git commit -m "Deploy to GitHub Pages"
              git push -f origin gh-pages
            else
              echo "No changes to commit"
            fi

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
